name: check-whitespace-push

# Get the repository with all commits to ensure that we can analyze
# all Pushes except in master branch.
# Process `git log --check` output to extract just the check errors.
# Exit with failure upon white-space issues.

on:
  push:
    branches-ignore:
      - master

permissions:
  contents: read

jobs:
  check-whitespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: git log --check origin/master..HEAD
